use failure::Error;

pub fn start() -> Result<(), Error> {
    Ok(())
}
